### PR TITLE
stacktrace: attach stack trace to error instance

### LINKED ISSUE #118: attach stack trace to error object

### PR DESCRIPTION
**Pull request by legendecas**
Expected behavior:
```js
function namedFunction () {
  return new Error('foobar')
}

console.log(namedFunction())
// Error: foobar
//     at namedFunction (/some/where/the/script/locates.js:1:10)


function capturePlainObject () {
  var e = {}
  Error.captureStackTrace(e)
  return e
}

console.log(capturePlainObject().stack)
//     at capturePlainObject (/some/where/the/script/locates.js:10:10)
```

close #118

### CODE REVIEW

File: src/js/iotjs.js [hunk 1]
```diff
@@ -54,7 +54,6 @@
     try {
       var loc = '/tmp/iotjs.' + process.pid;
       lines = fs.readFileSync(loc).toString().split('\n');
-      fs.unlinkSync(loc);
```
[the remark this answers is not in the document]
Comment (legendecas) [reply src/js/iotjs.js]: If we do remove this dump file, we can only get file read at the first time and failed afterwards.
Since dump file would be written continuously while new JS files are read in, it shall not be cached yet, in this case.

File: src/js/iotjs.js [hunk 2]
```diff
@@ -196,56 +197,41 @@
...
+      enumerable: false,
+      get: function () {
+        if (this.__stack__ === undefined) {
+          process._flushParserDumpFile();
+          this.__stack__ = makeStackTraceFromDump(this.__frames__);
+        }
+        return this.__stack__;
+      },
+    },
+    __stack__: {
```
[the remark this answers is not in the document]
Comment (legendecas) [reply src/js/iotjs.js]: As `__stack__` is a backing field of `stack`, the naming might be ok.

[the remark this answers is not in the document]
Comment (yorkie) [reply src/js/iotjs.js]: > As __stack__ is a backing field of stack

Suggestion: just using `_stack` for this purpose :)

[the remark this answers is not in the document]
Comment (yorkie) [reply src/js/iotjs.js]: BTW, `__proto__` is not forwarding to `proto`, actually Object doesn't own a `proto` object.

File: src/js/iotjs.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (yorkie) [reply src/js/iotjs.js]: This should be called when the program gets crashed, so dump file might not be used any more? Could you please point me out where we use this file in another place?

File: deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c [hunk 3]
```diff
@@ -134,6 +135,32 @@ ecma_new_standard_error (ecma_standard_error_t error_type) /**< native error typ
...
+  jerry_value_t jframes = jerry_create_array(depth);
+  for (uint32_t i = 0; i < depth; ++i) {
+    jerry_set_property_by_index(jframes, i, jerry_create_number(frames[i]));
+  }
+
+  free(frames);
+
+  prop_value_p->value = jframes;
+  ecma_deref_object (ecma_get_object_from_value (jframes));
+
```
[the remark this answers is not in the document]
Comment (legendecas) [reply deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c]: Since error stack trace has to be started with `JERRY_CONTEXT.vm_top_context_p`, a `jerry_*` api has to be called in this case.
Or is there any way can pass through `JERRY_CONTEXT` to access current top vm context?

File: src/js/iotjs.js [hunk 4]
```diff
@@ -196,56 +197,41 @@
...
+      configurable: true,
+      writable: true,
+      enumerable: false,
+    },
+  };
+  Object.defineProperties(Error.prototype, stackPropertiesDescriptor);
```
[the remark this answers is not in the document]
Comment (legendecas) [reply src/js/iotjs.js]: If the properties are not attached to the prototype, how can we get all error instance got the property `stack` without modifying native `Error` constructor and sharing the same stack generating code in JS?
The prototype changing of native types has to be prevented in cases of implementing our own API, however `error.stack` is a commonly used property in JS, it might be ok.

File: src/js/iotjs.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (legendecas) [reply src/js/iotjs.js]: In this implementation, stacks are generated from parser dump file with an array of frames.
Like examples I stated in issue description, it is possible that multiple error instances' stack accessed in a single run. And since the scripts are loaded with `require` continuously, the parser dump file does get new contents too.
Thus it is required to not remove the dump file to get error stacks in newly loaded scripts be generated correctly.

File: deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c [hunk 5]
```diff
@@ -134,6 +135,32 @@ ecma_new_standard_error (ecma_standard_error_t error_type) /**< native error typ
...
+                                                                         frames_str_p,
+                                                                         ECMA_PROPERTY_CONFIGURABLE_WRITABLE,
+                                                                         NULL);
+  ecma_deref_ecma_string (frames_str_p);
+
+  uint32_t depth = 10;
+  // create frames
+  uint32_t *frames = malloc(sizeof(uint32_t) * depth);
+  memset(frames, 0, sizeof(uint32_t) * depth);
+  jerry_get_stacktrace_depth(frames, depth);
```
Comment (yorkie) [inline deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c]: `jerry_get_stacktrace_depth()` is defined at [here](https://github.com/Rokid/ShadowNode/blob/e6ced3744bf3bcc8d44ef90edaafebb545b5012c/deps/jerry/jerry-core/api/jerry.c#L3392), and I think we could move the implementation into `jcontext`, and in jerry-core/api/jerry.c, we just call the internal impl as the following:

```c
void
jerry_get_stacktrace_depth (uint32_t *frames, uint32_t depth)
{
  jerry_assert_api_available ();
  return JERRY_BACKTRACE_DEPTH(frames, depth);
}
```

File: deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c [hunk 6]
```diff
@@ -134,6 +135,32 @@ ecma_new_standard_error (ecma_standard_error_t error_type) /**< native error typ
...
+
+  jerry_value_t jframes = jerry_create_array(depth);
+  for (uint32_t i = 0; i < depth; ++i) {
+    jerry_set_property_by_index(jframes, i, jerry_create_number(frames[i]));
+  }
```
Comment (yorkie) [inline deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c]: We shouldn't call the high-level API, namely the `jerry_*` in its submodule like ecma, so may I ask you to change to use the relevant methods under `jerry-core/ecma`.

File: deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (yorkie) [reply deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c]: See the above comments of mine, I think in ecma, call jcontext looks acceptable. Then we need to move some code into [jcontext.h](https://github.com/Rokid/ShadowNode/blob/e6ced3744bf3bcc8d44ef90edaafebb545b5012c/deps/jerry/jerry-core/jcontext/jcontext.h), and call those from there :)

File: deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c (hunk 5 above)
Comment (yorkie) [reply deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c]: BTW, the stacktrace are not regular naming rule in JerryScript, let's use `backtrace` to keep consistent with the community :)

File: src/js/iotjs.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (yorkie) [reply src/js/iotjs.js]: Ok, looks good to me now, and only one question we need to acquire, when do we clean this dump file up, in our past case, @lolBig give a feedback about this, when the program exits and restarts in a infinite loop, the dump file will be generated every circle, that eats the disk up to empty.

File: src/js/iotjs.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (yorkie) [reply src/js/iotjs.js]: Good point, a false `enumerable` value is reasonable and you has added it in the latest patch :p

File: test/run_pass/test_iotjs_error_stack.js [hunk 7]
```diff
@@ -0,0 +1,19 @@
+var assert = require('assert');
+
+var error = getError();
+assert(typeof error.stack === 'string');
+assert(error.stack.match(/^    at getError/));
```
Comment (yorkie) [inline test/run_pass/test_iotjs_error_stack.js]: A little suggestion, could we changing this match rule to simple `/at GetError/`? That don't make me in trouble whenever we tweak the spaces :)

File: test/run_pass/test_iotjs_error_stack.js [hunk 8]
```diff
@@ -0,0 +1,19 @@
...
+
+var plain = getPlainObject();
+assert(typeof plain.stack === 'string');
+assert(error.stack.match(/^    at getPlainObject/));
```
Comment (yorkie) [inline test/run_pass/test_iotjs_error_stack.js]: Ditto :)

File: deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c [hunk 9]
```diff
@@ -134,6 +136,42 @@ ecma_new_standard_error (ecma_standard_error_t error_type) /**< native error typ
...
+
+  ecma_property_value_t *prop_value_p = ecma_create_named_data_property (new_error_obj_p,
+                                                                         frames_str_p,
+                                                                         ECMA_PROPERTY_CONFIGURABLE_WRITABLE,
+                                                                         NULL);
+  ecma_deref_ecma_string (frames_str_p);
+
+  uint32_t depth = 10;
+  // create frames
+  uint32_t *frames = malloc(sizeof(uint32_t) * depth);
```
Comment (yorkie) [inline deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c]: Should check the result of `malloc()` like the following:

```c
uint32_t *frames = malloc (frames_size);
if (frames == NULL)
{
  // throw errors
}
memset (frames, 0, frames_size);
```

File: deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c [hunk 10]
```diff
@@ -134,6 +136,42 @@ ecma_new_standard_error (ecma_standard_error_t error_type) /**< native error typ
...
+    ecma_string_t *str_idx_p = ecma_new_ecma_string_from_uint32 ((uint32_t) i);
+    ecma_property_value_t *index_prop_value_p = ecma_create_named_data_property (array_p,
+                                                                           str_idx_p,
+                                                                           ECMA_PROPERTY_CONFIGURABLE_WRITABLE,
+                                                                           NULL);
+    ecma_deref_ecma_string (str_idx_p);
+    index_prop_value_p->value = ecma_make_uint32_value(frames[i]);
+  }
+
+  free(frames);
```
Comment (yorkie) [inline deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c]: Use `JERRY_ASSERT` to make sure the frames are malloc-ed successfully :)

File: deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c [hunk 11]
```diff
@@ -134,6 +136,42 @@ ecma_new_standard_error (ecma_standard_error_t error_type) /**< native error typ
...
+  uint32_t *frames = malloc(sizeof(uint32_t) * depth);
+  memset(frames, 0, sizeof(uint32_t) * depth);
+  jcontext_get_backtrace_depth(frames, depth);
+
+  ecma_value_t frames_array_length_val = ecma_make_uint32_value (depth);
+  ecma_value_t frames_array = ecma_op_create_array_object (&frames_array_length_val, 1, true);
+  ecma_free_value (frames_array_length_val);
+  ecma_object_t *array_p = ecma_get_object_from_value (frames_array);
+
+  for (uint32_t i = 0; i < depth; ++i) {
```
Comment (yorkie) [inline deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c]: Let's follow the coding style of JerryScript, put the left-bracket `{` on the next new line.

File: deps/jerry/jerry-core/jcontext/jcontext.c [hunk 12]
```diff
@@ -51,6 +51,18 @@ jerry_hash_table_t jerry_global_hash_table;
 #endif /* !CONFIG_ECMA_LCACHE_DISABLE */
 #endif /* !JERRY_ENABLE_EXTERNAL_CONTEXT */
 
+void
+jcontext_get_backtrace_depth (uint32_t *frames, uint32_t depth) {
```
Comment (yorkie) [inline deps/jerry/jerry-core/jcontext/jcontext.c]: Please fix the coding style as well :)

File: deps/jerry/jerry-core/jcontext/jcontext.c [hunk 13]
```diff
@@ -51,6 +51,18 @@ jerry_hash_table_t jerry_global_hash_table;
...
+  vm_frame_ctx_t *ctx_p = JERRY_CONTEXT (vm_top_context_p);
+  for (uint32_t idx = 0; idx < depth && ctx_p != NULL; ++idx) {
```
Comment (yorkie) [inline deps/jerry/jerry-core/jcontext/jcontext.c]: Ditto.

File: src/js/iotjs.js [hunk 14]
```diff
@@ -196,56 +194,41 @@
...
-      CallSite.create('main', ['<anonymous>', 4, 7]),
-    ];
+    return makeStackTraceFromDump(throwable._frames || []);
   }
 
+  var stackPropertiesDescriptor = {
+    stack: {
+      configurable: true,
+      enumerable: false,
+      get: function () {
```
Comment (yorkie) [inline src/js/iotjs.js]: Tweak to `get: function() {` :)

File: src/js/iotjs.js [hunk 15]
```diff
@@ -196,56 +194,41 @@
...
-    Object.defineProperties(throwable, {
-      stack: {
-        configurable: true,
-        get: function () {
-          return prepareStackTrace(throwable);
-        }
-      },
-      cachedStack: {
+    var frames = process._getStackFrames(11).slice(1);
+    Object.defineProperties(throwable, Object.assign({
```
Comment (yorkie) [inline src/js/iotjs.js]: Could we split the complex expression like this:

```js
var descriptor = Object.assign({
  _frames: {
    configurable: true,
    writable: true,
    enumerable: false,
    value: frames,
  },
}, stackPropertiesDescriptor);
Object.defineProperties(throwable, descriptor);
```

That might be more clear for maintainer :)

Comment (yorkie) [reply src/js/iotjs.js]: BTW, about the descriptor properties, 

- `configurable` might be false is OK?
- `writable` should be false? I didn't see any place we make re-assignment on `this._frames`.

Comment (yorkie) [reply src/js/iotjs.js]: Why user need to change this value?

File: deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c [hunk 16]
```diff
@@ -134,6 +136,45 @@ ecma_new_standard_error (ecma_standard_error_t error_type) /**< native error typ
...
+  ecma_free_value (frames_array_length_val);
+  ecma_object_t *array_p = ecma_get_object_from_value (frames_array);
+
+  for (uint32_t i = 0; i < depth; ++i)
+  {
+    ecma_string_t *str_idx_p = ecma_new_ecma_string_from_uint32 ((uint32_t) i);
+    ecma_property_value_t *index_prop_value_p = ecma_create_named_data_property (array_p,
+                                                                                 str_idx_p,
+                                                                                 ECMA_PROPERTY_CONFIGURABLE_WRITABLE,
+                                                                                NULL);
```
Comment (yorkie) [inline deps/jerry/jerry-core/ecma/operations/ecma-exceptions.c]: 2 spaces missed :(

**Comment by legendecas** [comment]
Looks like CI failed for `uncaughtException handler throws: AssertionError: {"actual":"connect failed - status: ETIMEDOUT: developer.rokid.com","expected":"get did fail","operator":"==="}`. Is developer.rokid.com down?

**Comment by yorkie** [comment]
Awesome works! Thanks @legendecas 💯
